### PR TITLE
Added snap option

### PR DESCRIPTION
**Pull request by davidruisinger**
Following my comment on http://market.ionic.io/plugins/ionic-scroll-sista
I added support for the header to snap back if user did not scroll far enough to fully hide the header.

### CODE REVIEW

**Comment by djett41** [comment]
Nice thanks!  I'll take a look later tonight.  I'm still trying to picture the difference between snapback true and false though.  Would it be hard to upload a short video of the differences?  Or of the snap feature?  And what would be a reason for someone not wanting this?  

Thanks again @flavordaaave !

**Comment by davidruisinger** [comment]
I only introduced the attribute with snap=true/false to only have the snap feature if someone explicitly wants so because I'm not 100% sure wether my implementation works for every use case.
I'll try to shoot a short video tomorrow to demonstrate this feature.

**Comment by djett41** [comment]
@flavordaaave I pulled down the branch, set the new attribute to true right next to scroll-sista, and was emulating in chrome with touch events but didn't notice a difference in functionality.  If you could get a short vid out that would be awesome so I could understand the feature before I merge it in.  Thanks!

**Comment by davidruisinger** [comment]
@djett41 Sorry for the delay. Here's a short video showing the difference. First you see the normal implementation where the user could only scroll a little and keep the header in the "half-hidden-state".
Then I turned on the snap feature which basically always snaps back to fully show the header as long as the user did not scroll enough to fully hide the header:
https://youtu.be/21884p0Vbvo

**Comment by djett41** [comment]
Thanks @flavordaaave !! I like it.  I dont see why we would want this to be an additional configuration, I think it should just be the default behavior since this is how it is in alot of other apps as well, good work!!

I only issue I am seeing is that if you scroll and it snaps back, then scroll slowly up again, sometimes the elements jump a little instead of scroll smooth 1 by 1.  

I'm not sure if this is a result of the feature code, or if this was always present and just not noticeable until now but I would like to get that resolved before adding this in.  But thanks again its great!  I can take a hack at it tomorrow.

**Comment by davidruisinger** [comment]
Great! And THX for the feedback. I'll try to find some time to have a look at the scrolling issue as well.

**Comment by djett41** [comment]
no prob @flavordaaave Thanks again!!!

**Comment by renatojava** [comment]
Hello, I am trying use with nested ion-content and ion-slide-box and it dont work.
This ion-view is into a tab;
ion-tab > ion-view > ion-content > ion-slide-box > ion-slide  > ion-content scroll-sista

**Comment by davidruisinger** [comment]
I'm sorry but I currently just don't have the time to look into this... But feel free to use my fork to build on.

**Pull request closed without merging**
